services:
  localstack:
    image: localstack/localstack
    container_name: localstack_terraform_local
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,dynamodb
      - DEBUG=0
    volumes:
      - localstack_terraform_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_terraform_data:
