[project]
name = "azure-container-apps"
version = "0.1.0"
description = "Azure Container Apps + Dapr + CosmosDB MVE"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "python-dotenv",
]
