[project]
name = "minio-docker-boto3"
version = "0.1.0"
description = "MinIO example with Docker and Boto3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "pandas",
    "pyarrow",
    "python-dotenv",
]
