[project]
name = "redis-docker-mutex"
version = "0.1.0"
description = "Minimal viable example for Redis distributed mutex with Docker and Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "redis>=5.0.1",
    "python-dotenv>=1.0.0",
]
