AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda S3 Uploader MVE

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-bucket

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: upload-to-s3
      Handler: lambda.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.12
      Code:
        S3Bucket: lambda-deploy-bucket
        S3Key: lambda.zip
      Environment:
        Variables:
          ENDPOINT_URL: http://localhost:4566
