[project]
name = "azure-cosmos-db"
version = "0.1.0"
description = "Minimal viable example for Azure Cosmos DB with Docker"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "python-dotenv",
    "azure-cosmos",
]
